### ISSUE TITLE
sesman-browser--sensor-function: Symbol’s function definition is void: end

### ISSUE THREAD

**Issue by rnikander** [vspinu/sesman#14]
I keep seeing this in my `*Messages*` buffer and minibuffer.

    sesman-browser--sensor-function: Symbol’s function definition is void: end
    redisplay--pre-redisplay-functions: (void-function end)

I'm not very familiar with emacs lisp so I'm not sure what else I can do to debug this.

The package manager says I have sesman 0.3.3 from melpa-stable. I'm running GNU Emacs 26.1 on macOS.

**Comment by vspinu** [comment]
This probably has to do with a buggy implementation of `when-let*` on your system. [This](https://github.com/vspinu/sesman/blob/master/sesman-browser.el#L240) is the only place where this error can occur. I have removed the use of `when-let*` and tagged the new stable release. Please let me know if you still see it.
