### ISSUE TITLE
error: Package 'sesman-0.3.2' is a system package, not deleting

### ISSUE THREAD

**Issue by sulemankm** [vspinu/sesman#21]
Hi, I've just installed spacemacs and when packages installation completes, I get this error.

`
Warning (initialization): An error occured while loading '/home/username/.emacs.e/init.el':

error: Package 'sesman-0.3.2' is a system package, not deleting

To ensure normal operation, you should investigate and remove the
....
`

Anybody having any idea, what could be causing this?

**Comment by vspinu** [comment]
No idea. Never seen such an error with any package. Probably spacemacs thingy. If you just delete it manually things should go to normal I bet.
