### ISSUE TITLE
Lingering reference to `sesman-ensure-linked-session`

### ISSUE THREAD

**Issue by ghost** [vspinu/sesman#4]
`sesman-restart` calls `sesman-ensure-linked-session`, but that function was renamed in commit 0f86bd3d34a2144e52014a4423da78d3faa7588e to `sesman-ensure-session`; this causes `sesman-restart` to produce the following message: `sesman-restart: Symbol’s function definition is void: sesman-ensure-linked-session`

I found that a simple rename fixed the issue locally, but I don't have a patch or PR to submit.

**Comment by vspinu** [comment]
Thanks!
