### ISSUE TITLE
Implement session browser infrastructure 

### ISSUE THREAD

**Issue by vspinu** [vspinu/sesman#5]
The idea. Generic `sesman-session-info` should return a string representation of a session or a list of the form `(:objects list-of-objects :strings list-of-string-representations-of-objects :map key-map)`. Then browser providers could use the above to construct hierarchical views of the sesman sessions. Particularly, the built-in browser will create buttons for each object within a session with the local `key-map` on it. 

`:strings` and `:map` are optional. Commands in `:map` should accept one argument - an object.

**Comment by bbatsov** [comment]
Yeah, that sounds reasonable.
