### ISSUE TITLE
Can't CIDER jack-in after update

### ISSUE THREAD

**Issue by nwjsmith** [vspinu/sesman#6]
After the `20180726.1443` update I get the following error when running `cider-jack-in`:

```
error in process filter: sesman--system: No ‘sesman-system’ in buffer ‘*cider-uninitialized-repl*’
error in process filter: No ‘sesman-system’ in buffer ‘*cider-uninitialized-repl*’
```

**Comment by manuel-uberti** [comment]
Same here, with latest `sesman` from MELPA.

**Comment by vspinu** [comment]
Yeh. This should be fixed on cider side. Sesman is not initialized early enough. Will fix asap.

**Comment by manuel-uberti** [comment]
Thanks, just updated. It's working now.

**Comment by nwjsmith** [comment]
The update works for me, thank you!
