### ISSUE TITLE
Commands to act on all sessions of the same type

### ISSUE THREAD

**Issue by bbatsov** [vspinu/sesman#7]
Yesterday I wanted to kill all my CIDER sessions and it seems there's no way to easily do this. Might also make sense to be able to restart all sessions, although killing sessions is certainly a much more common action. 

What do you think about adding some kill all sessions of type X command?

**Comment by vspinu** [comment]
There are 3 levels of kill and restart:  `sesman-quit` kill current session , `C-u sesman-quit` kill all linked sessions, `C-u C-u sesman-quit` kill all sessions. This is documented in `sesman-quit` and `sesman-restart` but not in the cider connection management doc. It might be worth adding. 

> What do you think about adding some kill all sessions of type X command?

What do you mean by "type"? Sessions don't have type beyond the system type (CIDER sessions, ESS sessions etc).

**Comment by vspinu** [comment]
Oups, `sesman-restart` doesn't have `which` argument. Must be added.

**Comment by bbatsov** [comment]
> What do you mean by "type"? Sessions don't have type beyond the system type (CIDER sessions, ESS sessions etc).

Yeah, exactly. I don't want to kill all my ESS and CIDER sessions together, but I'd often want to kill my ESS sessions or my CIDER sessions. Hopefully this makes sense.

**Comment by vspinu** [comment]
This is what's done by default. You cannot mess with ESS sessions from CIDER buffers. It should be possible to view all sessions for all systems from the session browser though.
