### ISSUE TITLE
Simplify "info" UI

### ISSUE THREAD

**Issue by vspinu** [vspinu/sesman#8]
Looks like current info commands (`sesman-show-session-info` and `sesman-show-links`) are  not up to the task. I think the following simple alternatives would work better:

  - `sesman-show-info` which would display links and sessions in a bit more comprehensive way than the current `sesman-show-links` does.
  - `sesman-browse-sessions` which would pop-up an interactive session browser

One extra advantage of the above is that C-c C-s C-l could be freed for a generic `sesman-link` (asking for type of context to link to).

**Comment by bbatsov** [comment]
Yeah, I agree that something along those lines would be a step in the right direction.
